### ISSUE TITLE
"local beatmap offset set" message appears unexpected when i touch on fingerprint sensor

### ISSUE THREAD

**Issue by LuisFellp** [fluddokt/opsu#250] opened 2018-04-25 22:45 UTC
when i was playing, this message has appeared and i have no idea how to reset this, when its appear the game sync goes extremely bad

please fix it or help me

**Comment by chutchatut** [comment] 2018-05-25 16:12
@LuisFellp same. Pixel 2 on Android P DP2.

**Comment by itdelatrisu** [comment] 2018-05-27 01:12
Duplicate of #247.

**Closed by itdelatrisu** 2018-05-27 01:12 UTC
Labels: duplicate

**Comment by chutchatut** [comment] 2018-05-27 01:41
Thanks

**Comment by fluddokt** [comment] 2018-06-14 00:54
Should be fixed in 0.16.1a

**Comment by Benik3** [comment] 2019-08-01 20:24
Hello.

Setting is fixed, but how to reset already set local offset? 

Thanks
