### ISSUE TITLE
Local offset problem

### ISSUE THREAD

**Issue by taylorlol1414** [fluddokt/opsu#260] opened 2018-05-26 16:28 UTC
When the fingerprint scanner on the back of phone is touched during gameplay the local offset plummets and there doesn't seem to be a way to fix it. Is there a way to reset the local offset or a command to speed it back up?

---
**Version:** 0.16.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@I23cc4685e6) (Qualcomm)
BOARD: msm8953
FINGERPRINT: Coolpad/alchemy/alchemy:7.1.1/143.14.171129.3701A-TMO/buildf_nj_02-206:user/release-keys
HOST: bf-nj-02
MODEL: REVVLPLUS C3701A
INCREMENTAL: eng.buildf.20171129.162853
RELEASE: 7.1.1

**Comment by itdelatrisu** [comment] 2018-05-27 01:12
Duplicate of #247.

**Closed by itdelatrisu** 2018-05-27 01:12 UTC

**Comment by fluddokt** [comment] 2018-06-14 00:54
Should be fixed in 0.16.1a
